### ISSUE TITLE
If passthrough is enabled there is no way to distinguish 403, 404 and 500

### ISSUE THREAD

**Issue by kamiltrebunia** [isaacs/st#27]
Because it is not possible to find out why a given file wasn't loaded it's impossible to handle it accurately.

README file states that it's essentially always 404, but after reading source code - that is clearly not the case as it may also be 403 and generic 500.

Obvious solution seems to be passing in 'er' as an argument into 'next' callback. Since st is using 'next' callback exclusively to announce errors (and never passes in any arguments anyway) it seems like it will not break any 3rd-party code.

Does that sound like a viable solution? Or can you think of any conflicts/drawbacks? If it's fine I would go ahead with implementation and pull request.

**Comment by rvagg** [comment]
closing due to age
