### ISSUE TITLE
Options to add default extention to path

### ISSUE THREAD

**Issue by Thomasdezeeuw** [isaacs/st#48]
I'm building a small cms that uses this module, it builds static pages before starting the server and then uses st to serve them. I was wondering if it would be possible to add a new option that added a default extention to path. That would allow me to have a nice url with having to modify it myself. For example

Going to `example.com/about` would check for `static/about/index.html` and normally return a 404. But instead it would add the extention, in this case `.html` and look for `static/about.html` and return that file (if present).

If this would be an acceptable change, I could submit a pr.

**Comment by rvagg** [comment]
closing due to age
