### ISSUE TITLE
First st module used can impact following st modules

### ISSUE THREAD

**Issue by neandrake** [isaacs/st#50]
In short: the st module sets a 'sturl' field on the http request object which will cause any further st modules to not look at the request.url field again (in case it's changed by an intermediate module).

In the setup I'm working on - the way the URL requests are designed to currently be handled:
- documents are served at /docs/:key
- static resources are accessible from the root path, '/index.html', '/app.js', etc.
- any request to '/:key' is redirected back to '/index.html', for which the app.js uses ajax to request the document with ':key' via the '/docs/:key' and populate the contents in places on the index.html page.

Example: 

``` javascript
var serveStaticFiles = st({
    url: '/',
    path: './static'
    passthrough: true
});
var serveApi = connectRoute(function(router) {
    /*
    get/post handlers for handling '/docs/' urls
    */
    // this is acts as a redirect so that the main application is sent back down and behavior can change client-side
    router.get('/:id', function(request, response, next) {
        request.url = '/index.html';
        // !! -- this doesn't work but it should -- !!
        next();
    });
});
var serveIndexFile = st({
    url: '/',
    path: './static',
    passthrough: false
});

var app = connect();
app.use(serveStaticFiles);
app.use(serveApi);
app.use(serveIndexFile);
```

What happens here when requesting '/mydocument':
- serveStaticFiles determines that ./static/mydocument does not exist
  -- the 'sturl' field on the request object is set to './static/mydocument'
- serveApi does not handle the url since it does not start with '/docs'
  -- the last handler changes the requested url to '/index.html' to send the application back
- serveIndexFile sees the 'sturl' field already exists on the request object which was previously resolved to './static/mydocument' and sends back 404 instead of looking at request.url which is now '/index.html'

To get around this issue, I am changing both request.url and request.sturl field in the last router.get() handler.

**Comment by rvagg** [comment]
closing due to age
