### ISSUE TITLE
ST 'passthrough' Does Not Work When 'index' Is Set To A Filename

### ISSUE THREAD

**Issue by dynamite-ready** [isaacs/st#55]
I currently use st with the following options:

```
var static = st({ 
path: rootDirectory + "/static", 
url:"/", 
index: "/index.html/",
passthrough: true,
gzip: true,
cache: false
});
```

I then:

```
application = connect().
use(static).
    use(someOtherMiddleware);

http.createServer(application).listen(80);
```

If I navigate to foo/bar, and '/bar' happens to contain an "index.html" file, then the application works as expected and the index.html file is served. If however, there's no index file inside '/bar', then the application 404's and the st "not found" page/message is served instead.

I would ideally prefer to have 'someOtherMiddleware' handle this case, but st ends the request instead of passing it through the Connect/Express pipeline, as suggested by the 'passthrough: true' parameter.

Is this a bug?

**Comment by rvagg** [comment]
closing due to age
