### ISSUE TITLE
Examples for Filtering Output?

### ISSUE THREAD

**Issue by joshgillies** [isaacs/st#57]
I wonder about the initial idea behind adding a filter stream to `res.filter`.

The docs indicate:

> This is useful if you want to get the benefits of caching and gzipping and such, but serve stylus files as css, for example.

But I'm having trouble visualising this actually coming together.

A way I've made use of this is:

``` js
var jadeStream = require('jade-stream')
var http = require('http')
var st = require('st')

var mount = st({
  path: 'app/assets',
  index: 'index.jade'
})

var app = http.createServer(function server(req, res) {
  if (req.url === '/')
    res.filter = jadeStream()

  mount(req, res)
})

app.listen(process.env.port, function listening() {
  var info = app.address()
  console.log('App running on http://%s:%s', info.address, info.port)
})
```

But given the fact that this will respond to http://localhost:8080/index.jade with the HTML page, it feels a little odd.

Has anyone an example of this in practice, and if not should it even be a feature of this module?

**Comment by rvagg** [comment]
Not I, but perhaps #56 would make the URL a little _less_ odd in this particular case

**Comment by joshgillies** [comment]
Ah, very interesting! Yeah that would remove the concern around HTML pages being returned for requests with a .jade extension. So `[index.jade, about.jade, faq.jade]` would map to `[index, about, faq]`, which would be fine. 

Given further thought I do see the utility in having a way to pass a filterStream to `res.filter`, especially if you were to use for example trumpet as a way to create dynamic pages while still benefiting from caching, gzipping, etc.

A more descriptive example in the docs would be good. Might knock something together over the coming days.

**Comment by rvagg** [comment]
closing due to age
