### ISSUE TITLE
Ability to specify error page in CLI

### ISSUE THREAD

**Issue by emilbayes** [isaacs/st#60]
I figured that I can override the requested page in case of an error like this:

``` js
mount(req, res, function() {
  req.sturl = '/index.html';
  mount(req, res);
});
```

However, it would be useful to have the ability to specify an error page when using the CLI, eg. to serve single page applications during development.

I'd love to submit a PR, but don't exactly know where to start.

**Comment by rvagg** [comment]
closing due to age
