### ISSUE TITLE
Enable setting Expires: header.

### ISSUE THREAD

**Issue by IngwiePhoenix** [isaacs/st#61]
It appears, that Google Chrome is pretty hot for ETags. When it finds one, it saves it, **but will then always do a validation request** instead of using a cached version.

Since the developer can specify a `max-age` value already, it should be possible to enable `Expires:` options also.

Even if the validation requests end up only being bytes of size, they _are_ requests that can be quite bothersome on a limited connection - say, a cellular connection with throttled connectivity on a low signal. Each request will bother the connection. The fewer, the better.

Would it be possible to implement that?

**Comment by rvagg** [comment]
How are `Expires` headers going to help here? `max-age` should be used in preference to `Expires` or does Chrome do something funky with them + etags?

**Comment by rvagg** [comment]
closing due to age
