### ISSUE TITLE
Best way to reduce validation requests

### ISSUE THREAD

**Issue by IngwiePhoenix** [isaacs/st#65]
I have quite a few resources that are stored in a `/cdn` path. This one might be mirrored through an actual CDN at one point, but while it isn't, I am using `st`.

The problem is, that when using ETags, the client sends a verification request. On a mobile connection, each additional request, even validation requests, count. So I wanted to know if there is a way to disable ETagging, so that the clients cache the content for the given time instead of trying to verify it.

If you have further suggestions for this matter, i'd be happy to hear them. :)

**Comment by rvagg** [comment]
Have you played with the cache-control headers? have a look at the README for `cacheControl`, also `content.maxAge` is used in the settings for this if you don't explicitly supply a `cacheControl` option.

**Comment by rvagg** [comment]
closing due to age
