### ISSUE TITLE
403 forbidden when file path contains dotted path component

### ISSUE THREAD

**Issue by pmuellr** [isaacs/st#67]
I have a case where the resultant path that a resource is being looked up on, is in a path that contains a dotted component, eg: `/Users/me/.MyApp/files/favicon.ico`.  I don't have the mount's `opt.dot` file set, and so when the code path gets here https://github.com/isaacs/st/blob/v0.5.5/st.js#L240 , it ends up falling in the if block and returning a forbidden response.

```js
  if (p === 403 || !this.opt.dot && p.match(/(^|\/)\./)) {
    res.statusCode = 403
    res.end('Forbidden')
    return true
  }
```

Is this really the intent of the `opt.dot` option - to check the complete path of the resource being looked up?  Seems more likely the intention is just to check the URL - eg, `req.url` at this point is `/favicon.ico`.

So, one of two things:

* If the intention is to just check the URL, let's fix the code to check `req.url` (or similar) at this point.

* If the intention is to check the complete path, suggest we add a new option `opt.dotFullPath` or similiar, which would check the full path (default: false), and change the `opt.dot` check to just check the `req.url` (or similar).  Existing clients will work the same as they always did.  But now, I can leave `dot.opt` false - no dotted paths files will be returned - and set `opt.dotFullPath` to allow my case of the full path having dotted path components.

I'm happy to provide a PR for either.  Or consider other options.

**Comment by rvagg** [comment]
I'd accept a patch to just check `req.url`, I don't see the sense in doing it for the full path cause if you're programmatically supplying that path then you're expressing your intention as a user of `st` and it's no longer a security issue. It'd have to be a semver-major though unfortunately.
