### ISSUE TITLE
index option unresponsive to 'true' or 'index.html'

### ISSUE THREAD

**Issue by sprjr** [isaacs/st#79]
Hello,

Just gave this a shot for a micro project:

``` js
const st = require('st');
const http = require('http');
const mount = st({
  path: `${__dirname}/build`,
  index: true
});

http.createServer(function(req, res) {
  var stHandled = mount(req, res);
  if (stHandled)
    return
  else
    res.end('this is not a static file')
}).listen(1338)
```

And I'm consistently unable to get `index.html` served by default for `/`. It does serve just fine if I explicitly if I append `/index.html` to the URL.

<img width="437" alt="new_guy" src="https://cloud.githubusercontent.com/assets/682566/17454155/3cb4c2d6-5b41-11e6-9c78-811348f71f85.png">

I can dig in a bit further and see if there's anything else I'm doing wrong - this is on node@6.3.1 / npm@3.10.3, but wanted to see if there was anything I'm missing from the examples/docs first. It looks like I should be able to set that `st()` config to either `true` or `index.html` in order to avoid directories being served.

**Comment by rvagg** [comment]
closing due to age
